### ISSUE TITLE
Reformatting does not abide by project's Code Style.

### ISSUE THREAD

**Issue by noel-yap** [wlsc/idea-junit-5-converter-plugin#22]
**Describe the bug**
When a project's Code Style specifies indentations of 2 spaces, the plugin reformats the code with 4-space indents.

**To Reproduce**
0. Set indentation to 2 spaces.
1. Go to 'Tools'
2. Click on 'Convert to JUnit 5'
3. View one of the test files that was converted.
4. Observe that the indentation is using 4 spaces.

**Expected behavior**
Indentation (and other style settings) should be followed.

**Screenshots**
Before conversion:
![image](https://user-images.githubusercontent.com/1414385/78180649-eef00a80-7417-11ea-9ecf-05fefa734f8a.png)

After conversion:
![image](https://user-images.githubusercontent.com/1414385/78180737-0cbd6f80-7418-11ea-8466-6590a519f617.png)

**Desktop (please complete the following information):**

**Comment by wlsc** [comment]
Thanks @noel-yap for reporting this issue. 
Yes indeed, it reformats the original source code according to some strange formatter which is not the current active one.

**Comment by wlsc** [comment]
Currently I am on the topic and rewriting the plugin to use Intellij IDEA tree walker to modify source code.

**Comment by wlsc** [comment]
well, after a some break from the project. I've decided to take another look at the problem of formatting a document after all modification were applied.
I will apply IDEA's code formatter feature to format modified code according to the current active code style formatter.
_Note here_: if the current formatter doesn't match original file format, it **won't** consider the old format, but active format will be applied.
Soon I will compose a PR with these changes.

**Comment by wlsc** [comment]
this PR should fix the issue https://github.com/wlsc/idea-junit-5-converter-plugin/pull/27

**Comment by wlsc** [comment]
Merging it in couple of hours.

**Comment by wlsc** [comment]
The fix has been merged.
