### ISSUE TITLE
Reduce scope of tests

### ISSUE THREAD

**Issue by jamakal** [wlsc/idea-junit-5-converter-plugin#23]
**Describe the solution you'd like**
Given that JUnit 5 classes and methods do not need to be public, it would be great to reduce the scope of these to default

N.b. Thank you very much for the plugin, once the code-formatter bug is fixed I will definitely be using it actively!

**Comment by wlsc** [comment]
@JamKage hi and thank you for the proposed change! Today I've merged fix to master for the formatter bug (https://github.com/wlsc/idea-junit-5-converter-plugin/issues/22). In day or two plugin will be released and version 1.3.2 will have that fix.

**Comment by wlsc** [comment]
@JamKage I've created a PR for such feature here https://github.com/wlsc/idea-junit-5-converter-plugin/pull/28

**Comment by jamakal** [comment]
@wlsc awesome, thanks for that!

**Comment by wlsc** [comment]
Merged linked PR, Closing this issue.
Will be available in the next 1.4.0 version.
