### ISSUE TITLE
Remove unnecessary 'throws' Exceptions after converting to assertThrows

### ISSUE THREAD

**Issue by jamakal** [wlsc/idea-junit-5-converter-plugin#25]
**Describe the solution you'd like**
When a method is converted which has an expected Exception (`@Test(expected = ...)`), the method signature of the resulting conversion still throws this Exception, even if it can no longer be thrown. In many cases, this 'throws' will no longer be necessary and can be removed.

**Additional context**
For example, the following class:

```java
import org.junit.Test;

import java.io.IOException;

public class TestTest {

    @Test(expected = IOException.class)
    public void test() throws IOException {
        testMethod();
    }

    public String testMethod() throws IOException {
        throw new IOException();
    }
}
```

will be converted to:

```java
import org.junit.jupiter.api.Test;
import java.io.IOException;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.extension.ExtendWith;

@DisplayName("Test Test")
public class TestTest {

    @Test
    @DisplayName("Test")
    public void test() throws IOException {
        assertThrows(IOException.class, () -> {
            testMethod();
        });
    }

    public String testMethod() throws IOException {
        throw new IOException();
    }
}
```

Note the unnecessary `throws IOException` is still present, even though there is no longer anything which can throw it

**Comment by wlsc** [comment]
hey @JamKage! this was fixed in the PR (https://github.com/wlsc/idea-junit-5-converter-plugin/pull/29) and available in the version 1.4.1
